server:
  port: 8989
  servlet:
    context-path: /users

spring:
  application:
    name: users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootvue?characterEncoding=UTF-8
    username: root
    password: W09059895x
mybatis:
  type-aliases-package: com.example.demo.entity

